#!/bin/sh

FULL_ARGS=$@
printf "Agent full arguments: $FULL_ARGS\n"
export TIME=$1
export SITE=$2
export TIMEOUT=$3
shift 3
ARGUMENTS=$@

if [ -f /bin/rpm ]; then
	printf "Agent TIMEOUT_CMD does not support -k\n"
	TIMEOUT_CMD=timeout
else
	TIMEOUT_CMD="timeout -k 10"
fi

printf "Agent ($SITE) passing arguments: $ARGUMENT\n"

run_test()
{
	rm -rf ./report.txt
	chmod +x ./test
	$TIMEOUT_CMD $TIMEOUT ./test $ARGUMENTS
}

clean_data()
{
	rm -rf `pwd`
}

clean_test()
{
	find . | grep -v "\.$" | grep -v "report\." | xargs rm -rf
	rm -rf `pwd`.tar /tmp/remote_agent
}

run_test
#clean_data
clean_test
